// Generated by `flutterfire configure` for the study-routine-89990 Firebase
// project. Re-run `flutterfire configure --project=study-routine-89990` if
// platforms or apps change — don't hand-edit the values below.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` to generate real options.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm48mrPUTZvFjOZkVEoUOvrbArvqigNzk',
    appId: '1:46402901436:web:571c2b28def770953f47b9',
    messagingSenderId: '46402901436',
    projectId: 'study-routine-89990',
    authDomain: 'study-routine-89990.firebaseapp.com',
    storageBucket: 'study-routine-89990.firebasestorage.app',
    measurementId: 'G-JSPBFHLVSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6kPKsnhFfyvHq99u__mtOvhAZvHH6Cs',
    appId: '1:46402901436:android:0392fb601b7e212b3f47b9',
    messagingSenderId: '46402901436',
    projectId: 'study-routine-89990',
    storageBucket: 'study-routine-89990.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKFvbwi_5RMS8wZykLiNoZzsj6zIREQA',
    appId: '1:46402901436:ios:adfee1ab393661883f47b9',
    messagingSenderId: '46402901436',
    projectId: 'study-routine-89990',
    storageBucket: 'study-routine-89990.firebasestorage.app',
    iosBundleId: 'com.example.studyRoutine',
  );
}
